# Generated by Django 5.0.7 on 2024-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedlink',
            name='url_name',
            field=models.CharField(default=models.URLField(), max_length=30),
        ),
    ]
